         ---
- name: Check and Start Service if Needed
  hosts: managed_nodes
  become: true
  vars:
    service_name: apache2 
    email_recipient: "dhayadhaya1707@gmail.com"

  tasks:
    - name: Gather service facts
      service_facts:

    - name: install the service
      apt:
        name: "{{service_name}}"
        state: latest
      when: service_name not in ansible_facts.services

    - name: Start the service if it is not running
      service:
        name: "{{ service_name }}"
        state: started
      when: 
        - service_name in ansible_facts.services
        - ansible_facts.services[service_name].state != 'running'
      register: service_action

    - name: Send service notification email
      mail:
        host: "localhost"
        to: "{{ email_recipient }}"
        subject: "Service Status Notification"
        body: |
          The {{ service_name }} service is currently {% if service_action.changed %}not running and has now been started{% else %}running{% endif %} on {{ ansible_hostname }}.
