---

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates(Ubuntu) 
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:  

  - name: install updates (Ubuntu)
    tags: apache,aapache2,Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install httpd and php for CentOS
    tags: httpd,php,CentOS 
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"   

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (CentOS)
    tags: mariadb,CentOS
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: mariadb,Ubuntu
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks: 
  
  - name: install samba package
    tags: samba,CentOS,Ubuntu
    package:
      name: samba
      state: latest
