- name: install apache and php packages    
  tags: httpd,php,CentOS,apache2
  package:
    name:
      - "{{apache_package_name}}"
      - "{{php_package_name}}"
    state: latest
 
- name: start httpd service for CentOS
  tags: httpd,apache2,CentOS
  service:
    name: "{{apache_service}}"
    state: started
  when: ansible_distribution == "CentOS"
 
- name: change email addres for admin
  tags: httpd,apache,CentOS
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin dhayadhaya1707@gmail.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache
 
- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

 
