- name: install mariadb package(CentOS)
  tags: CentOS,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb server package (Ubuntu)
  tags: Ubuntu,mariadb,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
